name: Firebase hosting
on: 
  workflow_run:
    workflows: ["Main tests"]
    branches:
      - main
    types:
      - completed
jobs:
  deploy:
    if: ${{ (github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VESSEL_WEBAPP }}'
          projectId: vessel-webapp
          channelId: live
  on_failure:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'failure') }}
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Build cannot be deployed because not all tests passed')
