name: Firebase preview
on: 
  workflow_run:
    workflows: ["Development tests"]
    branches:
      - development
    types:
      - completed
jobs:
  build_and_deploy:
    if: ${{ (github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VESSEL_WEBAPP }}'
          projectId: vessel-webapp
          channelId: 'pr-development-preview'
  on_failure:
    runs-on: ubuntu-latest
    if: ${{ (github.event.workflow_run.conclusion == 'failure') }}
    steps:
      - uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Preview build cannot be deployed because not all tests passed')
