name: Development tests
on: 
 pull_request:
    branches: [development]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - run: npm ci && npm test
